# Github Action for deploy page
#
# Copileft (c) by Eduard Gafurov 2022.
#------------------------------
name: CiCd-for-Deploy
env:
  APPLICATION_NAME    : "MyFlask"
  DEPLOY_PACKAGE_NAME : "Flask_deploy_ver-${{ github.sha }}"

on:
  push:
    branches: 
      - main
      
jobs:
  my-testing:
    runs-on: ubuntu-latest
    
    steps:
      - name: Print Hello Message in Testing
        run : echo "Hello World from Testing"
        
      - name: Execure few commands
        run: |
          echo "Hello Message1"
          echo "Hello message2"
          echo "Application name ${{ env.APPLICATION_NAME }}"
          
      - name: List current folder
        run: ls -la
      
      - name: Git clone my repo
        uses: actions/checkout@v1
        
      - name: List current folder after clone
        run: ls -la  
    
  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-testing]
    
    steps:
      - name: Print Hello Message in Deploy
        run : echo "Hello World from Deploy"
        
      - name: Printing Deployment package
        run: echo "Deploy package name is ${{ env.DEPLOY_PACKAGE_NAME }}"
        
      - name: Lets test some packages
        run: aws --version
        
      - name: Lets test some packages 2
        run: zip  
